// Regenerates src/data.ts from Google libphonenumber's Japanese numbering plan.
// Run with `npm run generate`.
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const OUT = join(
	dirname(fileURLToPath(import.meta.url)),
	"..",
	"src",
	"data.ts",
);

const scratch = mkdtempSync(join(tmpdir(), "lpn-jp-"));
const jsonPath = join(scratch, "metadata.json");

const cli = require.resolve(
	"libphonenumber-metadata-generator/bin/generate-metadata.js",
);
const log = execFileSync(
	process.execPath,
	[cli, jsonPath, "--countries", "JP", "--with-phone-number-types"],
	{
		encoding: "utf8",
	},
);

const version = log.match(/Metadata version:\s*(\S+)/)?.[1];
if (!version)
	throw new Error(
		"could not read the metadata version from the generator output",
	);

const json = JSON.parse(readFileSync(jsonPath, "utf8"));
rmSync(scratch, { recursive: true, force: true });

const [country, ...others] = Object.keys(json.countries);
if (country !== "JP" || others.length)
	throw new Error(
		`expected Japan and nothing else, got: ${[country, ...others].join(", ")}`,
	);
const plan = json.countries[country];
if (json.country_calling_codes["81"]?.length !== 1) {
	throw new Error(
		"calling code 81 is no longer Japan alone; the parser assumes it is",
	);
}

// Field positions in libphonenumber-js's compressed metadata; see its METADATA.md.
const [
	callingCode,
	iddPrefix,
	nationalNumberPattern,
	possibleLengths,
	formats,
	nationalPrefix,
	nationalPrefixFormattingRule,
	nationalPrefixForParsing,
	nationalPrefixTransformRule,
	nationalPrefixIsOptionalWhenFormatting,
	,
	types,
] = plan;
const extPrefix = plan[13] ?? " ext. ";

if (callingCode !== "81")
	throw new Error(`unexpected calling code ${callingCode}`);

// The full ISO country list, so that code written against libphonenumber-js
// still typechecks after switching imports. Types are erased at build time, so
// this costs nothing in the bundle.
const json5 = (value) => JSON.stringify(value);

const body = `// Generated by tools/generate.mjs -- do not edit.
// Google libphonenumber's Japanese numbering plan, flattened out of the shape
// libphonenumber-js stores it in. Apache License 2.0; see
// third_party/LICENSE-libphonenumber.

/** The libphonenumber release this data was generated from. */
export const METADATA_VERSION = ${json5(version)}

export const CALLING_CODE = ${json5(callingCode)}
/** Prefix dialled before a country code to call out of Japan. */
export const IDD_PREFIX = ${json5(iddPrefix)}
/** The trunk prefix: the "0" a national-format number starts with. */
export const NATIONAL_PREFIX = ${json5(nationalPrefix)}
/** Matched against the start of a number to strip the trunk prefix and any carrier code. */
export const NATIONAL_PREFIX_FOR_PARSING = ${json5(nationalPrefixForParsing || nationalPrefix)}
export const NATIONAL_PREFIX_TRANSFORM_RULE = ${json5(nationalPrefixTransformRule || undefined)}
export const NATIONAL_PREFIX_IS_OPTIONAL_WHEN_FORMATTING = ${json5(!!nationalPrefixIsOptionalWhenFormatting)}
export const NATIONAL_PREFIX_FORMATTING_RULE = ${json5(nationalPrefixFormattingRule || undefined)}
/** Every national number, of any type, matches this. */
export const NATIONAL_NUMBER_PATTERN = ${json5(nationalNumberPattern)}
/** Lengths a national number is allowed to have, ascending. */
export const POSSIBLE_LENGTHS: readonly number[] = ${json5(possibleLengths)}
export const EXT_PREFIX = ${json5(extPrefix)}
/** A valid Japanese number, for getExampleNumber(). */
export const EXAMPLE_NUMBER = ${json5(require("libphonenumber-js/examples.mobile.json").JP)}

/**
 * Grouping rules, most specific first: the pattern the national number must
 * match entirely, the \`$1-$2\` replacement, the leading digits that select the
 * rule, the rule that puts the trunk prefix back, and the international
 * variant when it differs.
 */
export type Format = readonly [
  pattern: string,
  format: string,
  leadingDigits?: readonly string[] | 0,
  nationalPrefixFormattingRule?: string | 0,
  nationalPrefixIsOptionalWhenFormatting?: 0 | 1,
  internationalFormat?: string | 0,
]

export const FORMATS: readonly Format[] = ${json5(formats)}

/** Patterns per number type, in libphonenumber's own order. See TYPE_NAMES. */
export type TypePattern = readonly [pattern: string, possibleLengths?: readonly number[] | 0]

export const TYPES: readonly (TypePattern | 0)[] = ${json5(types)}

/**
 * The only country this package carries. Passing any other one is a type error
 * rather than something that quietly resolves to nothing at run time.
 */
export type CountryCode = ${json5(country)};
`;

writeFileSync(OUT, body);
console.log(`wrote ${OUT} (${body.length} bytes, libphonenumber ${version})`);
